# Generated by Django 6.0.4 on 2026-05-07 19:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('envios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenServicio',
            fields=[
                ('pedido_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nro_pedido', models.CharField(editable=False, max_length=20, unique=True)),
                ('cantidad_encomiendas', models.PositiveIntegerField(default=0)),
                ('peso_total_kg', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('costo_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('estado', models.IntegerField(choices=[(1, 'Pendiente'), (2, 'Procesando'), (3, 'Completada'), (4, 'Cancelada')], default=1)),
                ('notas', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_servicio', to='clientes.cliente')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_creadas', to=settings.AUTH_USER_MODEL)),
                ('empleado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_registradas', to='envios.empleado')),
            ],
            options={
                'verbose_name': 'Orden de Servicio',
                'verbose_name_plural': 'Órdenes de Servicio',
                'db_table': 'ordenes_servicio',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='ItemOrdenServicio',
            fields=[
                ('item_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nro_item', models.PositiveIntegerField(default=1)),
                ('codigo_encomienda', models.CharField(max_length=20)),
                ('descripcion', models.TextField()),
                ('peso_kg', models.DecimalField(decimal_places=2, max_digits=8)),
                ('costo_envio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('encomienda', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='item_orden', to='envios.encomienda')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='envios.ordenservicio')),
            ],
            options={
                'db_table': 'items_orden_servicio',
                'ordering': ['nro_item'],
            },
        ),
    ]
